version: "3"
services:
  pms:
    image: loph3xertoi/pms:latest
    container_name: pms
    environment:
      # -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
      _JAVA_OPTIONS: >
        -Xdebug
        -Dspring.profiles.active=prod
      SPRING_CONFIG_ADDITIONAL-LOCATION: /data/secrets.yml
    ports:
      - "443:443"
      # - "5005:5005"
    volumes:
      - ./pms:/data
    networks:
      - net
    depends_on:
      - redis
      - mysql
      - qqmusic-api
      - ncm-api
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
      - ./redis/backup:/etc/redis/backup
    networks:
      - net
    command: redis-server /etc/redis/redis.conf
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'playlist_master'
      MYSQL_USER: 'pms'
      MYSQL_PASSWORD: 'pms'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/logs/error.log:/var/log/mysql/mysql.log
    networks:
      - net
    command: --default-authentication-plugin=mysql_native_password
  qqmusic-api:
    container_name: qqmusic-api
    image: loph3xertoi/qqmusic-api:latest
    restart: always
    ports:
      - "3300:80"
    networks:
      - net
  ncm-api:
    container_name: ncm-api
    image: loph3xertoi/netease-music-api:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - net
networks:
  net:
