#Global configurations
global:
  scrape_interval: 1h # Set the scrape interval to every 5 seconds.
  evaluation_interval: 1h # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    #    basic_auth:
    #      username: "prometheus"
    #      password: "prometheus"
    #    tls_config:
    #      ca_file: pms.crt
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'playlistmaster.fun:443' ]
