name: Build and Deploy PMS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "build-deploy"
  cancel-in-progress: false

jobs:
  build-deploy:
    name: Build and Deploy PMS docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK 8
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Install Maven Dependencies
        run: mvn dependency:resolve

      # - name: Unit Tests
      #   run: mvn -B test -f pom.xml

      - name: Build PMS
        run: mvn -DskipTests -B package -f pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5.0.0
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pms:latest

      - name: Deploy to Remote Server
        uses: loph3xertoi/docker-remote-deployment-action@v1
        with:
          remote_docker_host: root@playlistmaster.fun
          ssh_private_key: ${{ secrets.REMOTE_SERVER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.REMOTE_SERVER_SSH_PUBLIC_KEY }}
          docker_registry_username:  ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          # docker_registry_uri: https://registry.hub.docker.com
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/app
          stack_file_name: docker-compose.yml
          keep_files: 5
          args: -p pms up -d
          docker_prune: true
          pull_images_first: true
          docker_compose_down: true

      
      # - name: Start Deployment
      #   uses: TapTap21/docker-remote-deployment-action@v1.1
      #   with:
      #     remote_docker_host: root@playlistmaster.fun
      #     ssh_private_key: ${{ secrets.REMOTE_SERVER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.REMOTE_SERVER_SSH_PUBLIC_KEY }}
      #     stack_file_name: docker-compose.yml
      #     docker_login_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #     docker_login_user: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     # docker_login_registry : https://registry.hub.docker.com/v2/
      #     args: -p pms up -d

      # - name: Deploy PMS
      #   uses: wshihadeh/docker-deployment-action@v1
      #   with:
      #     remote_docker_host: root@playlistmaster.fun
      #     ssh_private_key: ${{ secrets.REMOTE_SERVER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.REMOTE_SERVER_SSH_PUBLIC_KEY }}
      #     deployment_mode: docker-compose
      #     copy_stack_file: true
      #     deploy_path: /root/app
      #     stack_file_name: docker-compose.yml
      #     keep_files: 5
      #     args: up -d
      #     docker_prune: 'true'
      #     pull_images_first: 'true'
          